### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by kkyuri0419** [NVIDIA-Omniverse/web-viewer-sample#8]
Hi,

I am following quick start guide step by step and when I did "npm install"
it gives me errors as below:
```
npm ERR! code ENOLOCAL
npm ERR! Could not install from "node_modules\@nvidia\omniverse-webrtc-streaming-library\deps\@gamestream\core" as it does not contain a package.json file.
```

How can I fix this?

**Comment by qscgyujm** [comment]
I have same issue when I run "npm install"
How did yout fix this?
